language: ruby
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.2
sudo: false
addons:
  code_climate:
    repo_token:
      secure: "W4ox654Q5LVwk1jNunNCquRSMq2bIumFVyTNgs8Gp8QS+fUNwBAMnh+dUnSsMLjGi8Ix304nwhK0yoXj0pehiRgaoYf1j64+NXHFw56jO4RfDvVSbD2jCnUZsPwxE4YPNOQLNOig2XOoggh4bJFJ96U1UlWCdSm6Up4LN598N6uLafcPbDkjS9xCVb8vdLNg6wAXPGDitJ25qSgbeNl0L/Qcw+f1YBi/lQUEhAD6qUpJ2R4buU5ZpOEpHf1U/4h0XyFDnPtUStDeMbdtbiDWEtVvM6qSWLzE9fGLimlY7oP58NeaNRbxuCSbPper3lGTaGZVqYnD052l9PeVRTUwaCPdzNLQ+dDWyT6EE+jv3DoYwnLudvezC6/sxRyADfGjg+bA1wWzU8qb5eLUuYvzswrzyxI6dd3fQIjscdYEZW/wxHciMaDUsj13YIIv4Y0o19J+xEfE+RKSSnuxYeZXO3HhrcCGxiYRJUBeQti4rFxtiIuNpbogG0IAVQNOYaMTgIY2jZ5PWGSj7Sub3m0NWzSDEg6eG1+vv2CTTbgpViaFUkW9ssC647GHjEnJCBtMOC04ENUSw8spnmyHRm1oprjbjWHYJk0XYx+besS4Ed7n1qtL/aTvcIKLC7YGaZC3pUob4UESq4EZeAbRdGAEcU4LNfoGvV1Yny6hB2Hk7BQ="
