language: ruby
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.2
sudo: false
secure: "nSxK7dOsD+OYJBXuzJFqOQr5k1C54XKZJwEvrNxoMtrISxeDMWPgnvXvBE8T0EQvZVidWCn8aZXBSzZeleUWZzsheDkRrR2SBlVcJhXqpjt+6ez0NUPnbHqrnRrsq9JvQWA1tN2oSfpFnuJC3zvDJWw7Ar3Z7YpUU7mk/HfMhCuNBtTQ2AdcUKSRD6Szadarwl08bv0Oop5hULRYSx6Zf70InZqntWiLnBtMo5v/FrEpVR/RXcOUaX+GT+l7oXAIz0R+30rq6K2KCqT0Xszh2IrZDoEOfT0BPlR6cMCfCPmUxbtbgaC1JnV/QimFLk5hlFDrjnWUSygUBtPTjT99XOnV/YC0y27O3JMX7spQgSZfFZIpsXGLAlkZlwIpyzoCZnQmC3CFuGCuYVgZln4kNTdjBWVf0nkLrg/daE2rlzN4qabE/j1G+YIFSQFqJzZUDy3gOe0fktRgsMbNafmg05w88KDnKupx3DYb+lhPKgKGqJ84fC/REd8FPng4IqcaBV2yrPQBtglqdqBhca0em1XwqlktJ0Q+r7c7MCppg3Ys+6LkYDXoC7ei0d82IFzllgxoHCNSFlxrgGTw2CwovmGPqDttkrizsz9qg+3YZQDNIP3CHZv9hBdz83gmognS0i+mXudc8dWsywhTJZGpVLOUp0mm8rGLJKcqfJQr8GE="
